modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="simplest_emerald_gear"
version="1.0.5"
displayName="Simplest Emerald Gear"
authors="Team Solar"
description='''Emerald armor and tools.'''
logoFile="logo.png"

[[dependencies.simplest_emerald_gear]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.simplest_emerald_gear]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"